var arrayGroup = [
      ["100 MONTADITOS                ", "Otros"]
    , ["100MONTADITOS                 ", "Otros"]
    , ["A.S. - AP-6 VILLA             ", "Automóvil"]
    , ["CRED PAU VALLECAS             ", "Automóvil"]
    , ["AGENCIA ESTATAL DE LA ADMINIST", "Hacienda"]
    , ["AHORRAMAS                     ", "Otros"]
    , ["ALDI                          ", "Otros"]
    , ["ALIMEN.PROSPERIDAD            ", "Otros"]
    , ["GESTION BARRAS 6 BCL          ", "Otros"]
    , ["TIO LUCAS                     ", "Otros"]
    , ["CARNI.DEHESA GRAN             ", "Otros"]
    , ["PANADERIA DEL AGUIL           ", "Otros"]
    , ["CENTRO EURO HIPER Z           ", "Otros"]
    , ["RESTAURANTE SAPPORO           ", "Otros"]
    , ["ALLDEBRID.COM                 ", "Alldebrid"]
    , ["FERRT Y DECOR LAS S           ", "Caprichos"]
    , ["LA TIENDA DE NIKO             ", "Caprichos"]
    , ["NOISE CULT LIVE               ", "Caprichos"]
    , ["OBM RIVAS                     ", "Caprichos"]
    , ["SumUp  *Lepoka                ", "Caprichos"]
    , ["AMAZON                        ", "Caprichos"]
    , ["AMZN Mktp ES                  ", "Caprichos"]
    , ["APETECEME SALAMAN             ", "Otros"]
    , ["APOR.                         ", "Plan Pensión"]
    , ["ASCENSOR   SUBCOMUNIDAD 1C    ", "SubComunidad"]
    , ["ATRACCIONES CA                ", "Caprichos"]
    , ["AUTOPISTA R4 SEITT -          ", "Automóvil"]
    , ["AVANZI                        ", "Farmacía"]
    , ["AYTTO DE S754645 150010121279 ", "Contribución"]
    , ["AYTTO DE S972617 158880085800 ", "Contribución"]
    , ["AYUDA A CASA                  ", "Casero"]
    , ["Amazon.es                     ", "Caprichos"]
    , ["Amazon.es                     ", "Caprichos"]
    , ["BASE BRAVO SL                 ", "Otros"]
    , ["BAZAR YUAN JUN                ", "Caprichos"]
    , ["BEBES ESTUDIO COMPLETA,       ", "Caprichos"]
    , ["BENAD                         ", "Farmacía"]
    , ["BM ENSANCHE DE VALLE          ", "Otros"]
    , ["BRACO SPESIALTY COFF          ", "Otros"]
    , ["C830 C D LA GAVIA             ", "Otros"]
    , ["CAFE PRINCIPE PIO             ", "Otros"]
    , ["CARL'S JR                     ", "Otros"]
    , ["CARNICERIA ANTONIO            ", "Otros"]
    , ["CARREF                        ", "Otros"]
    , ["CRF EXPRESS                   ", "Otros"]
    , ["CC LA GAVIA LOCAL B1          ", "Otros"]
    , ["CC. LA GAVIA                  ", "Otros"]
    , ["CEDIPSA VILLAL                ", "Automóvil"]
    , ["CERVE.SLAINTE                 ", "Otros"]
    , ["CHIRINGUITO SALINAS           ", "Otros"]
    , ["CHURRERIA AVENIDA             ", "Otros"]
    , ["COPYSUR BLAS INFANT           ", "Caprichos"]
    , ["CUOTA ABRIL  PLAN UNI SEGUR   ", "Casero"]
    , ["CUOTA AGOSTO  PLAN UNI SEGUR  ", "Casero"]
    , ["CUOTA DICIEMBRE  PLAN UNI SEGU", "Casero"]
    , ["CUOTA ENERO  PLAN UNI SEGUR   ", "Casero"]
    , ["CUOTA FEBRERO  PLAN UNI SEGUR ", "Casero"]
    , ["CUOTA JULIO  PLAN UNI SEGUR   ", "Casero"]
    , ["CUOTA JUNIO  PLAN UNI SEGUR   ", "Casero"]
    , ["CUOTA MARZO  PLAN UNI SEGUR   ", "Casero"]
    , ["CUOTA MAYO  PLAN UNI SEGUR    ", "Casero"]
    , ["CUOTA NOVIEMBRE  PLAN UNI SEGU", "Casero"]
    , ["CUOTA OCTUBRE  PLAN UNI SEGUR ", "Casero"]
    , ["CUOTA SEPTIEMBRE  PLAN UNI SEG", "Casero"]
    , ["Castellana de Autopistas      ", "Automóvil"]
    , ["DADOS Y CUBITOS               ", "Caprichos"]
    , ["DECATHLON                     ", "Caprichos"]
    , ["DELIKIA SP                    ", "Otros"]
    , ["DEVAS 2                       ", "Otros"]
    , ["DEVOLUCIONES TRIBUTARIAS, AGEN", "Hacienda"]
    , ["DIA                           ", "Otros"]
    , ["DONER KEBAP VILLA             ", "Otros"]
    , ["DUNKIN COFFEE LAS GA          ", "Otros"]
    , ["E. LECLERC VALDEM             ", "Automóvil"]
    , ["E.LECLERC VALDEMO             ", "Automóvil"]
    , ["E.S. CEDIPSA ARANJ            ", "Automóvil"]
    , ["E.S. ORCASITAS                ", "Automóvil"]
    , ["E.S. STA. CRUZ                ", "Automóvil"]
    , ["E.S.NUEVA MAYPA S.L.          ", "Automóvil"]
    , ["EESS VALLECAS DAC             ", "Automóvil"]
    , ["EL CORNER DE BRINDIS          ", "Otros"]
    , ["EL CORTE INGLES               ", "Caprichos"]
    , ["ELHA                          ", "Depilación"]
    , ["ENTRADAS EVENTOS              ", "Caprichos"]
    , ["EXPAVDAALFONSOVI              ", "Otros"]
    , ["EXPPOETAPACOAQUINO            ", "Otros"]
    , ["EXPPORTIV                     ", "Otros"]
    , ["FARM. ROSA FDEZ. VEG          ", "Farmacía"]
    , ["FARMA.BLAS INFANTE            ", "Farmacía"]
    , ["FARMA.MERCEDES MARTI          ", "Farmacía"]
    , ["FARMACIA                      ", "Farmacía"]
    , ["FARMACIA DRA. M.J. MELGAR     ", "Farmacía"]
    , ["FARMACIA MERCEDES             ", "Farmacía"]
    , ["FARMAVOS                      ", "Farmacía"]
    , ["FARMA.RIVAS EX                ", "Farmacía"]
    , ["FAUNIA - TPV PC               ", "Caprichos"]
    , ["FCC AQUALI472603 875010009854 ", "Agua"]
    , ["FCC Aquali472603 875010009854 ", "Agua"]
    , ["FEVER* MARVEL UNIVERSE        ", "Caprichos"]
    , ["FIVE GUYS SPAIN SL            ", "Otros"]
    , ["FNAC LA GAVIA VALLEC          ", "Caprichos"]
    , ["FRUTERIA Y ALIMENTA           ", "Otros"]
    , ["FRUTOS SECOS                  ", "Otros"]
    , ["GAME 189 SALAM                ", "Caprichos"]
    , ["GANESHA COMBUSTIBLES          ", "Automóvil"]
    , ["GAS NATURA015991 000047279891 ", "Luz"]
    , ["GASOL.LECLERC                 ", "Automóvil"]
    , ["GESTION PARQUE ANI.T          ", "Caprichos"]
    , ["GOG.com                       ", "Caprichos"]
    , ["HOSPITAL CLINICO              ", "Otros"]
    , ["HOSPITAL DE VALLECAS          ", "Otros"]
    , ["HOSTAL-REST. EL SERRANO       ", "Otros"]
    , ["HOTEL NOVOTEL MADRID          ", "Otros"]
    , ["IKEA ALMERIA HFB              ", "Caprichos"]
    , ["IKEA LA GAVIA HFB             ", "Caprichos"]
    , ["JUEGAVIA S.L.                 ", "Caprichos"]
    , ["KATEL REPARACIONES C          ", "Cocina"]
    , ["KEBAH NARVAEZ                 ", "Otros"]
    , ["LA COLECTIVA                  ", "Otros"]
    , ["LA COLOTA 13                  ", "Otros"]
    , ["LA FONDA DE LA ES             ", "Otros"]
    , ["LEFTIES                       ", "Caprichos"]
    , ["LEROY MERLIN L                ", "Caprichos"]
    , ["LEROY MERLIN R                ", "Caprichos"]
    , ["LIDL LA RAMBLA                ", "Otros"]
    , ["LIDL MAD-VILLA DE VA          ", "Otros"]
    , ["LIDL RIVAS VACIA              ", "Otros"]
    , ["LIDL SALAMANCA                ", "Otros"]
    , ["LSD 24H GRANADA               ", "Otros"]
    , ["MADRID SUR MOVILIDAD          ", "Automóvil"]
    , ["MANOLO BAKES GAVIA            ", "Otros"]
    , ["MARKET ALMERIA                ", "Otros"]
    , ["MC DONALDS                    ", "Otros"]
    , ["MERCADONA                     ", "Otros"]
    , ["MINISO LIFESTYLE SPA          ", "Caprichos"]
    , ["NATURGYC  0144GD 000000919608 ", "Luz"]
    , ["NUEVO MINIMARKET              ", "Otros"]
    , ["NYX*AIRservSpain              ", "Automóvil"]
    , ["Naturgy Iberia, S.A           ", "Luz"]
    , ["Naturgy Clientes, S.A.U.      ", "Luz"]
    , ["OCIONACIONAL MARTIN,          ", "Otros"]
    , ["ORION                         ", "Automóvil"]
    , ["PAGO COMUNIDAD 1C             ", "Comunidad"]
    , ["PAGO DE COMUNIDAD.            ", "Comunidad"]
    , ["PAGO DE SUBCOMUNIDAD.         ", "Comunidad"]
    , ["PAGO HIPTECA                  ", "Casero"]
    , ["PAN ALMERIA S.L.              ", "Otros"]
    , ["PAN CAFETERIA DEL A           ", "Otros"]
    , ["PAYPAL *LAPOSADADEL           ", "Caprichos"]
    , ["PAYPAL *LEROYMERLIN           ", "Caprichos"]
    , ["PAYPAL *LEROYMERLIN           ", "Caprichos"]
    , ["PAYPAL *THANGS 3D             ", "Caprichos"]
    , ["PIZZERIA CARLOS               ", "Otros"]
    , ["PRIMARK MADRID - LA GA        ", "Caprichos"]
    , ["REC.MCARD                     ", "delete"]
    , ["RENFE VIAJEROS APP            ", "Automóvil"]
    , ["REST.EL CORNER DEL            ", "Otros"]
    , ["RODILLA                       ", "Otros"]
    , ["SQ *ALIEXPRESS LA GAVI        ", "Caprichos"]
    , ["STAR WASH                     ", "Caprichos"]
    , ["SUBCOMINIDAD PAGO 1ºC         ", "SubComunidad"]
    , ["SUBCOMUNIDAD                  ", "SubComunidad"]
    , ["SUBWAY                        ", "Otros"]
    , ["Seguro Hogar 053909562        ", "Seguro"]
    , ["TALLERES ELOY                 ", "Automóvil"]
    , ["TECNIL GICA ECOSIS S.A.U.     ", "Nómina"]
    , ["TECNIL GICA ECOSISTEMAS, S.A.U", "Nómina"]
    , ["TECNILA GICA ECOSISTEMAS, S.A.", "Nómina"]
    , ["TECNILOGICA ECOSISTEMAS, S.A. ", "Nómina"]
    , ["TESORERIA GENERAL DE LA SEGURI", "Hacienda"]
    , ["TM *TICKETMASTER              ", "Caprichos"]
    , ["TRITON I                      ", "Otros"]
    , ["TRITON II                     ", "Otros"]
    , ["US289 PLENOIL ALMER           ", "Automóvil"]
    , ["VASCO DE GAMA                 ", "Otros"]
    , ["VENDING HOSPITAL              ", "Otros"]
    , ["VIRGEN DEL CARMEN             ", "Otros"]
    , ["VODAFONE                      ", "Internet"]
    , ["Vodafone                      ", "Internet"]
    , ["WHITE WEASEL STUDI            ", "Caprichos"]
    , ["WOK SALAMANCA                 ", "Otros"]
    , ["KFC                           ", "Otros"]
    , ["WWW.AMAZON.                   ", "Caprichos"]
    , ["seguro 053909562              ", "Seguro"]
    , ["www.groupon.es                ", "Caprichos"]
    , ["AISA YILIDU S,                ", "Caprichos"]
    , ["COPYSUR                       ", "Caprichos"]
    , ["PAYPAL *ALIPAY EUR            ", "Caprichos"]
    , ["ABADES                        ", "Otros"]
    , ["CAFETERIA                     ", "Otros"]
    , ["RESTAURANTE SAPPORO           ", "Otros"]
    , ["LA OVEJA NEGRA FOOD           ", "Otros"]
    , ["EL RINCON DEL JAMON           ", "Otros"]
    , ["OBRADOR DE GOYA               ", "Otros"]
    , ["IKEA LA GAVIA FOOD            ", "Otros"]
    , ["PLENERGY US289 ALME           ", "Automóvil"]
    , ["GANESHA COMBUSTI              ", "Automóvil"]
];